# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_title', models.CharField(max_length=200)),
                ('practice_content', models.ImageField(upload_to=b'')),
                ('practice_level', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=200)),
                ('question_content', models.ImageField(upload_to=b'')),
                ('question_answer1', models.CharField(max_length=200)),
                ('question_answer2', models.CharField(max_length=200)),
                ('question_answer3', models.CharField(max_length=200)),
                ('question_answer4', models.CharField(max_length=200)),
                ('question_right_answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_username', models.CharField(max_length=200)),
                ('student_password', models.CharField(max_length=32)),
                ('student_first_name', models.CharField(max_length=200)),
                ('student_family_name', models.CharField(max_length=200)),
                ('mark_shimi', models.FloatField()),
                ('mark_fizik', models.FloatField()),
                ('mark_hesaban', models.FloatField()),
                ('study_shimi', models.FloatField()),
                ('study_fizik', models.FloatField()),
                ('study_hesaban', models.FloatField()),
                ('sys_mark_shimi', models.FloatField()),
                ('sys_mark_fizik', models.FloatField()),
                ('sys_mark_hesaban', models.FloatField()),
                ('practice_shimi', models.FloatField()),
                ('practice_fizik', models.FloatField()),
                ('practice_hesaban', models.FloatField()),
            ],
        ),
    ]
