# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170621_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_password',
            field=models.CharField(default=1234, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_username',
            field=models.CharField(max_length=200),
        ),
    ]
