# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_auto_20170621_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mark_hesaban', models.FloatField()),
                ('mark_hendese', models.FloatField()),
                ('mark_arabi', models.FloatField()),
                ('student_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('practice_hesaban', models.FloatField()),
                ('practice_hendese', models.FloatField()),
                ('practice_arabi', models.FloatField()),
                ('student_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('study_hesaban', models.FloatField()),
                ('study_hendese', models.FloatField()),
                ('study_arabi', models.FloatField()),
                ('student_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SysMark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sys_mark_hesaban', models.FloatField()),
                ('sys_mark_hendese', models.FloatField()),
                ('sys_mark_arabi', models.FloatField()),
                ('student_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mark_fizik',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mark_hesaban',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mark_shimi',
        ),
        migrations.RemoveField(
            model_name='student',
            name='practice_fizik',
        ),
        migrations.RemoveField(
            model_name='student',
            name='practice_hesaban',
        ),
        migrations.RemoveField(
            model_name='student',
            name='practice_shimi',
        ),
        migrations.RemoveField(
            model_name='student',
            name='study_fizik',
        ),
        migrations.RemoveField(
            model_name='student',
            name='study_hesaban',
        ),
        migrations.RemoveField(
            model_name='student',
            name='study_shimi',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sys_mark_fizik',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sys_mark_hesaban',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sys_mark_shimi',
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
