# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20170621_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=200)),
                ('question_content', models.ImageField(upload_to=b'')),
                ('question_answer1', models.CharField(max_length=200)),
                ('question_answer2', models.CharField(max_length=200)),
                ('question_answer3', models.CharField(max_length=200)),
                ('question_answer4', models.CharField(max_length=200)),
                ('question_right_answer', models.CharField(max_length=200)),
            ],
        ),
    ]
