# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20170623_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=models.ImageField(upload_to='static/media/'),
        ),
    ]
