# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20170623_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmark',
            name='sys_mark_arabi',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='sysmark',
            name='sys_mark_hendese',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='sysmark',
            name='sys_mark_hesaban',
            field=models.FloatField(default=''),
        ),
    ]
