# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20170623_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmark',
            name='sys_mark_arabi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sysmark',
            name='sys_mark_hendese',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sysmark',
            name='sys_mark_hesaban',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
