# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20170623_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('practice_id', models.AutoField(primary_key=True, serialize=False)),
                ('practice_title', models.CharField(max_length=200)),
                ('question_lesson', models.CharField(default='', max_length=200)),
                ('practice_content', models.ImageField(upload_to='static/media/')),
                ('practice_level', models.CharField(max_length=200)),
            ],
        ),
    ]
