# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysmark',
            name='sys_mark_arabi',
        ),
        migrations.RemoveField(
            model_name='sysmark',
            name='sys_mark_hendese',
        ),
        migrations.RemoveField(
            model_name='sysmark',
            name='sys_mark_hesaban',
        ),
        migrations.AddField(
            model_name='sysmark',
            name='sys_mark',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sysmark',
            name='sys_mark_lesson',
            field=models.CharField(default='', max_length=200),
        ),
    ]
