# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20170624_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praclevel',
            name='practice_arabi',
        ),
        migrations.RemoveField(
            model_name='praclevel',
            name='practice_hendese',
        ),
        migrations.RemoveField(
            model_name='praclevel',
            name='practice_hesaban',
        ),
        migrations.AddField(
            model_name='praclevel',
            name='prac_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='praclevel',
            name='prac_level_lesson',
            field=models.CharField(default='', max_length=200),
        ),
    ]
