# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20170624_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='practice_content',
            field=models.ImageField(upload_to='web/static/media/practices'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=models.ImageField(upload_to='web/static/media/questions'),
        ),
    ]
