# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20170624_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice',
            old_name='question_lesson',
            new_name='practice_lesson',
        ),
    ]
