# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20170624_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='mark_arabi',
            new_name='mark_fizic',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='mark_hendese',
            new_name='mark_shimi',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='study_arabi',
            new_name='study_fizic',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='study_hendese',
            new_name='study_shimi',
        ),
    ]
