# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20180820_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='email_address',
        ),
    ]
